name: iOS App Deploy

on:
  push:
    branches: [main]

env:
  SUPABASE_URL_DEV_AND: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_URL_DEV_IOS: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_KEY_DEV: ${{ secrets.SUPABASE_KEY_PROD }}
  SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_KEY_PROD: ${{ secrets.SUPABASE_KEY_PROD }}
  CONFIGCAT_AND_TEST_KEY: ${{ secrets.CONFIGCAT_AND_TEST_KEY }}
  CONFIGCAT_AND_LIVE_KEY: ${{ secrets.CONFIGCAT_AND_LIVE_KEY }}
  CONFIGCAT_IOS_TEST_KEY: ${{ secrets.CONFIGCAT_IOS_TEST_KEY }}
  CONFIGCAT_IOS_LIVE_KEY: ${{ secrets.CONFIGCAT_IOS_LIVE_KEY }}
  GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
  APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
  MATCH_TYPE: appstore
  MATCH_APP_IDENTIFIER: uy.jorgemarquez.MisionVida
  MATCH_GIT_URL: https://github.com/japsystem/apple-certificates.git
  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSPHRASE }}
  MATCH_READONLY: true
  PILOT_APP_IDENTIFIER: uy.jorgemarquez.MisionVida
  PILOT_GROUPS: Internals

jobs:
  ios_tests:
    name: iOS Unit Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: SPM Cache
      uses: actions/cache@v4
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable

    - name: Set Up SDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Load Google Service PLIST file
      run: echo $GOOGLE_SERVICES_PLIST | base64 -d > iosApp/MisionVida/GoogleService-Info.plist

    - name: Set Up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        working-directory: iosApp

    - name: iOS Unit Tests (bundle exec)
      run: bundle exec fastlane tests

#    - name: iOS Unit Tests (Fastlane)
#      uses: maierj/fastlane-action@v3.1.0
#      with:
#        lane: tests
#        subdirectory: iosApp
#
#    - name: iOS Release to TestFlight
#      uses: maierj/fastlane-action@v3.1.0
#      with:
#        lane: release
#        subdirectory: iosApp

#    - name: Gather code coverage
#      run: xcrun llvm-cov export -format="lcov" .build/debug/{YOUR_PACKAGE_NAME}PackageTests.xctest/Contents/MacOS/{YOUR_PACKAGE_NAME}PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
#
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v5
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        fail_ci_if_error: fail
#        files: ./coverage_report.lcov
#        verbose: true
