name: Shared Tests & Lint

on: pull_request

env:
  SUPABASE_URL_DEV_AND: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_URL_DEV_IOS: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_KEY_DEV: ${{ secrets.SUPABASE_KEY_PROD }}
  SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
  SUPABASE_KEY_PROD: ${{ secrets.SUPABASE_KEY_PROD }}
  CONFIGCAT_AND_TEST_KEY: ${{ secrets.CONFIGCAT_AND_TEST_KEY }}
  CONFIGCAT_AND_LIVE_KEY: ${{ secrets.CONFIGCAT_AND_LIVE_KEY }}
  CONFIGCAT_IOS_TEST_KEY: ${{ secrets.CONFIGCAT_IOS_TEST_KEY }}
  CONFIGCAT_IOS_LIVE_KEY: ${{ secrets.CONFIGCAT_IOS_LIVE_KEY }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
  GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}

jobs:

  danger:
    name: Danger Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Danger
      uses: danger/kotlin@1.3.2
      with:
        dangerfile: config/Dangerfile.df.kts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  kotlin-check:
    name: Kotlin Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Set Up SDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Load Google Service JSON file
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > composeApp/google-services.json

    - name: Check Kotlin Formatting
      run: ./gradlew ktfmtCheck

    - name: Detekt Checks
      run: ./gradlew detektAll

  swift-check:
    name: Swift Static Analysis
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: SPM Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Load Google Service PLIST file
      run: echo $GOOGLE_SERVICES_PLIST | base64 -d > iosApp/Template/GoogleService-Info.plist

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Swift Format Check
      run: swiftformat --lint iosApp/ --config config/.swiftformat --reporter github-actions-log

    - name: Swift Lint
      run: swiftlint iosApp/ --strict --config config/.swiftlint.yml

  tests:
    name: Kotlin Unit Tests
    needs: kotlin-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Set Up SDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Load Google Service JSON file
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > composeApp/google-services.json

    - name: Konsist Tests
      run: ./gradlew konsistTest:test --rerun-tasks

      # Unit tests run when the gradle task koverVerify run.
      #    - name: Run Unit Tests
      #      run: ./gradlew :shared:cleanTestDebugUnitTest :shared:testDebugUnitTest --tests 'com.adriandeleon.template.*'

    - name: Check coverage metrics
      run: ./gradlew koverVerify koverXmlReport

    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: shared/build/reports/kover/report.xml
        disable_search: true
        fail_ci_if_error: true
